name: Makefile CI

on:
  push:
    branches: [master]
  pull_request:
    paths-ignore:
    - '.github/workflows/cmake.yml'
    - '.gitignore'
    - 'README'
    - '**README'
    - 'LICENSE'
    - 'CMAKE**'
    - '**CMakeLists.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  build-all:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout ScaLAPACK
      uses: actions/checkout@v2

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    - name: Install BLAS and LAPACK
      run: sudo apt -y install libblas-dev liblapack-dev

    - name: Build ScaLAPACK
      run: |
        cp SLmake.inc.example SLmake.inc
        # make -j is buggy; see #54.
        make lib
        make all

    - name: Run examples
      working-directory: ${{github.workspace}}/EXAMPLE
      run: |
        mpiexec -n 4 ./xsscaex
        mpiexec -n 4 ./xdscaex
        mpiexec -n 4 ./xcscaex
        mpiexec -n 4 ./xzscaex
